<#include "header.ftlh">

<div class="row">
    <div class="col-12" id="page_search">

        <form method="post" action="result">

            <input type="text" class="form-control" name="url" placeholder="https://itunes.apple.com/../playlist/..." required>
            <div id="divider"></div>
            <button type="submit" class="btn font-weight-light">SEARCH</button>

        </form>

    </div>
</div>

<#include "footer.ftlh">